#!/bin/bash
# AST Parameter Gating Safety Validation for Vitest Worker Threads
# Generated by XORAS Open Security Initiative

set -eo pipefail

TARGET_DIR="${1:-.}"
echo "=== XORAS Sentry: Scanning AST integrity in ${TARGET_DIR} ==="

# Check syntax validity of all JavaScript/TypeScript files in target
find "${TARGET_DIR}" -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" \) ! -path "*/node_modules/*" ! -path "*/dist/*" | while read -r file; do
    if ! node --check "${file}" 2>/dev/null; then
        echo "[ERR] Syntax error detected in: ${file}"
        exit 1
    fi
done

echo "[OK] AST validation scan complete. Zero syntax drift detected."
exit 0
