packages:
  - docs
  - packages/*
  - examples/*
  - test/*
  - test/config/fixtures/conditions-pkg

catalog:
  '@iconify-json/carbon': ^1.2.13
  '@iconify-json/logos': ^1.2.9
  '@jridgewell/remapping': ^2.3.5
  '@jridgewell/trace-mapping': 0.3.30
  '@types/chai': ^5.2.2
  '@types/debug': ^4.1.12
  '@types/estree': ^1.0.8
  '@types/istanbul-lib-coverage': ^2.0.6
  '@types/istanbul-lib-report': ^3.0.3
  '@types/istanbul-lib-source-maps': ^4.0.4
  '@types/istanbul-reports': ^3.0.4
  '@types/test-exclude': ^6.0.2
  '@types/ws': ^8.18.1
  '@unocss/reset': ^66.5.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': ^12.8.2
  acorn-walk: ^8.3.4
  birpc: ^2.5.0
  cac: ^6.7.14
  chai: ^6.0.1
  debug: ^4.4.1
  flatted: ^3.3.3
  istanbul-lib-coverage: ^3.2.2
  istanbul-lib-report: ^3.0.1
  istanbul-lib-source-maps: ^5.0.6
  istanbul-reports: ^3.2.0
  magic-string: ^0.30.19
  magicast: ^0.3.5
  msw: ^2.11.1
  pathe: ^2.0.3
  sirv: ^3.0.2
  std-env: ^3.9.0
  strip-literal: ^3.0.0
  test-exclude: ^7.0.1
  tinyglobby: ^0.2.15
  tinyrainbow: ^3.0.2
  unocss: ^66.5.1
  unplugin-vue-components: ^0.28.0
  vue: ^3.5.21
  ws: ^8.18.3
