import type { Task } from '@vitest/runner'
import type {
  BrowserTraceEntry,
  BrowserTraceEntryKind,
  BrowserTraceEntryStatus,
  BrowserTraceSelectorResolution,
  PseudoClassName,
} from '../../types'
import { getBrowserState, now } from '../utils'
import { rpc } from './rpc'

export type { BrowserTraceEntry, BrowserTraceEntryKind, BrowserTraceEntryStatus, BrowserTraceSelectorResolution }

export interface BrowserTraceData {
  retry: number
  repeats: number
  recordCanvas: boolean
  entries: BrowserTraceEntry[]
}

export interface BrowserTraceAttempt {
  retry: number
  repeats: number
  startTime: number
}

const PSEUDO_CLASS_NAMES = [
  ':hover',
  ':active',
  ':focus',
  ':focus-visible',
  ':focus-within',
] as const

export function recordBrowserTraceEntry(
  task: Task,
  options: Omit<BrowserTraceEntry, 'snapshot' | 'startTime'> & {
    startTime?: number
  },
): void {
  // TODO: trace-view currently receives selectors after locator/action resolution,
  // so provider-specific lowered selectors can leak into snapshot lookup. Preserve
  // the original locator selector, or record the target node id before lowering.
  // for example, this causes shadow dom selectors to fail with `>>>` marker.
  // For now, remove trivial `html >` prefix generated by convertElementToCssSelector.
  // this is also necessary to `engine.querySelector + document.documentElement`
  // to find an element on webdriverio
  if (options.selector?.startsWith('html >')) {
    options.selector = options.selector.slice(6)
  }
  const attemptInfo = getBrowserState().browserTraceAttempts.get(task.id)!
  const relativeStartTime = (options.startTime ?? now()) - attemptInfo.startTime
  const snapshot = takeSnapshot(options.selector)
  const entry: BrowserTraceEntry = {
    ...options,
    startTime: relativeStartTime,
    snapshot,
  }
  const { retry, repeats } = attemptInfo
  const { recordCanvas } = getBrowserState().config.browser.traceView
  rpc().streamBrowserTraceEntry(task.id, retry, repeats, recordCanvas, entry)
}

// Resolve ivya selector to a DOM element and take a snapshot with rrweb Mirror
// so we can store the nodeId for provider-agnostic element highlighting in the viewer.
// Note: Playwright's alternative approach is to store the raw selector and run the
// selector engine inside the snapshot iframe at view time via injected script.
// Our approach resolves at collection time (same moment as snapshot) — simpler but
// requires Mirror plumbing. nodeId-based lookup also works across shadow DOM, unlike querySelector.
function takeSnapshot(selector?: string): BrowserTraceEntry['snapshot'] {
  const { snapshot, createMirror } = getBrowserState().browserTraceDomSnapshot!
  const traceView = getBrowserState().config.browser.traceView
  const engine = getBrowserState().selectorEngine!
  const mirror = createMirror()
  const serialized = snapshot(document, {
    mirror,
    inlineImages: traceView.inlineImages,
    recordCanvas: traceView.recordCanvas,
  })
  const result: BrowserTraceEntry['snapshot'] = {
    serialized,
    viewport: {
      width: window.innerWidth,
      height: window.innerHeight,
    },
    scroll: {
      x: window.scrollX,
      y: window.scrollY,
    },
    pseudoClassIds: {} as any,
  }
  for (const className of PSEUDO_CLASS_NAMES) {
    const elements = document.querySelectorAll(className as PseudoClassName)
    const ids = Array.from(elements, el => mirror.getId(el)).filter(id => id !== -1)
    result.pseudoClassIds[className as PseudoClassName] = ids
  }
  if (selector) {
    try {
      const el = engine.querySelector(
        engine.parseSelector(selector),
        document.documentElement,
        false,
      )
      if (!el) {
        result.selectorResolution = 'missing'
      }
      else {
        const id = mirror.getId(el)
        if (id !== -1) {
          result.selectorId = id
          result.selectorResolution = 'matched'
        }
        else {
          result.selectorResolution = 'missing'
        }
      }
    }
    catch (error) {
      result.selectorResolution = 'error'
      result.selectorError = error instanceof Error ? error.message : String(error)
    }
  }
  return result
}
