import type { Task } from '@vitest/runner'
import { getBrowserState } from '../utils'

// TODO: review slop (NEVER REMOVE COMMENT)

export interface BrowserTraceData {
  retry: number
  repeats: number
  recordCanvas: boolean
  entries: BrowserTraceEntry[]
}

// TODO: timestamp
// TODO: duration (expect.element, actions, mark)
export type BrowserTraceEntryKind = 'action' | 'expect' | 'mark' | 'lifecycle'
export type BrowserTraceEntryStatus = 'pass' | 'fail'
export type BrowserTraceSelectorResolution = 'matched' | 'missing' | 'error'

export interface BrowserTraceEntry {
  name: string
  // not used yet for UI
  kind: BrowserTraceEntryKind
  status?: BrowserTraceEntryStatus
  stack?: string
  // resolved server-side from stack in __vitest_recordBrowserTrace command
  location?: { file: string; line: number; column: number }
  selector?: string
  snapshot: TraceSnapshot
}

interface TraceSnapshot {
  serialized: unknown
  viewport: {
    width: number
    height: number
  }
  scroll: {
    x: number
    y: number
  }
  selectorId?: number
  // not used yet for UI
  selectorResolution?: BrowserTraceSelectorResolution
  selectorError?: string
}

export interface BrowserTraceState {
  entries: Map<string, Map<string, BrowserTraceData>>
}

function getBrowserTraceState(): BrowserTraceState {
  return getBrowserState().browserTraceState ??= {
    entries: new Map(),
  }
}

function getAttemptKey(repeats: number, retry: number) {
  return `${repeats}:${retry}`
}

// TODO: should we avoid accumulating? send and immediately clear each entry to save memory?
export function recordBrowserTraceEntry(
  task: Task,
  options: Omit<BrowserTraceEntry, 'snapshot'>,
): void {
  // TODO: trace-view currently receives selectors after locator/action resolution,
  // so provider-specific lowered selectors can leak into snapshot lookup. Preserve
  // the original locator selector, or record the target node id before lowering.
  // for example, this causes shadow dom selectors to fail with `>>>` marker.
  // For now, remove trivial `html >` prefix generated by convertElementToCssSelector.
  // this is also necessary to `engine.querySelector + document.documentElement`
  // to find an element on webdriverio
  if (options.selector?.startsWith('html >')) {
    options.selector = options.selector.slice(6)
  }
  const snapshot = takeSnapshot(options.selector)
  const entry: BrowserTraceEntry = { ...options, snapshot }
  const { retry, repeats } = getBrowserState().browserTraceAttempts.get(task.id)!
  const { recordCanvas } = getBrowserState().config.browser.traceView
  const state = getBrowserTraceState()
  const attempts = state.entries.get(task.id) || new Map()
  const attemptKey = getAttemptKey(repeats, retry)
  const attempt = attempts.get(attemptKey) || { retry, repeats, recordCanvas, entries: [] }
  attempt.entries.push(entry)
  attempts.set(attemptKey, attempt)
  state.entries.set(task.id, attempts)
}

// Resolve ivya selector to a DOM element and take a snapshot with rrweb Mirror
// so we can store the nodeId for provider-agnostic element highlighting in the viewer.
// Note: Playwright's alternative approach is to store the raw selector and run the
// selector engine inside the snapshot iframe at view time via injected script.
// Our approach resolves at collection time (same moment as snapshot) — simpler but
// requires Mirror plumbing. nodeId-based lookup also works across shadow DOM, unlike querySelector.
function takeSnapshot(selector?: string): TraceSnapshot {
  const { snapshot, createMirror } = getBrowserState().browserTraceDomSnapshot!
  const traceView = getBrowserState().config.browser.traceView
  const engine = getBrowserState().selectorEngine!
  const mirror = createMirror()
  const serialized = snapshot(document, {
    mirror,
    inlineImages: traceView.inlineImages,
    recordCanvas: traceView.recordCanvas,
  })
  const result: TraceSnapshot = {
    serialized,
    viewport: {
      width: window.innerWidth,
      height: window.innerHeight,
    },
    scroll: {
      x: window.scrollX,
      y: window.scrollY,
    },
  }
  if (selector) {
    try {
      const el = engine.querySelector(
        engine.parseSelector(selector),
        document.documentElement,
        false,
      )
      if (!el) {
        result.selectorResolution = 'missing'
      }
      else {
        const id = mirror.getId(el)
        if (id !== -1) {
          result.selectorId = id
          result.selectorResolution = 'matched'
        }
        else {
          result.selectorResolution = 'missing'
        }
      }
    }
    catch (error) {
      result.selectorResolution = 'error'
      result.selectorError = error instanceof Error ? error.message : String(error)
    }
  }
  return result
}

export function getBrowserTrace(testId: string, repeats: number, retry: number): BrowserTraceData | undefined {
  const state = getBrowserTraceState()
  const attempts = state.entries.get(testId)
  if (!attempts?.size) {
    return
  }
  const attemptKey = getAttemptKey(repeats, retry)
  const attempt = attempts.get(attemptKey)
  if (!attempt) {
    return
  }
  attempts.delete(attemptKey)
  if (!attempts.size) {
    state.entries.delete(testId)
  }
  return attempt
}
