// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Navigation: typeof import('./components/Navigation.vue')['default']
    Suites: typeof import('./components/Suites.vue')['default']
    TestSuite: typeof import('./components/TestSuite.vue')['default']
  }
}

export { }
