// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Files: typeof import('./components/Files.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    StatusIcon: typeof import('./components/StatusIcon.vue')['default']
    Suites: typeof import('./components/Suites.vue')['default']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TestFile: typeof import('./components/TestFile.vue')['default']
    TestSuite: typeof import('./components/TestSuite.vue')['default']
  }
}

export { }
