/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserIframe: typeof import('./components/BrowserIframe.vue')['default']
    CodeMirrorContainer: typeof import('./components/CodeMirrorContainer.vue')['default']
    ConnectionOverlay: typeof import('./components/ConnectionOverlay.vue')['default']
    Coverage: typeof import('./components/Coverage.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DashboardEntry: typeof import('./components/dashboard/DashboardEntry.vue')['default']
    DetailsPanel: typeof import('./components/DetailsPanel.vue')['default']
    ErrorEntry: typeof import('./components/dashboard/ErrorEntry.vue')['default']
    Explorer: typeof import('./components/explorer/Explorer.vue')['default']
    ExplorerItem: typeof import('./components/explorer/ExplorerItem.vue')['default']
    FileDetails: typeof import('./components/FileDetails.vue')['default']
    FilterSelect: typeof import('./components/FilterSelect.vue')['default']
    FilterStatus: typeof import('./components/FilterStatus.vue')['default']
    IconAction: typeof import('./components/IconAction.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModuleTransformResultView: typeof import('./components/ModuleTransformResultView.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenshotError: typeof import('./components/views/ScreenshotError.vue')['default']
    StatusIcon: typeof import('./components/StatusIcon.vue')['default']
    TestFilesEntry: typeof import('./components/dashboard/TestFilesEntry.vue')['default']
    TestsEntry: typeof import('./components/dashboard/TestsEntry.vue')['default']
    TestsFilesContainer: typeof import('./components/dashboard/TestsFilesContainer.vue')['default']
    ViewConsoleOutput: typeof import('./components/views/ViewConsoleOutput.vue')['default']
    ViewConsoleOutputEntry: typeof import('./components/views/ViewConsoleOutputEntry.vue')['default']
    ViewEditor: typeof import('./components/views/ViewEditor.vue')['default']
    ViewModuleGraph: typeof import('./components/views/ViewModuleGraph.vue')['default']
    ViewReport: typeof import('./components/views/ViewReport.vue')['default']
    ViewReportError: typeof import('./components/views/ViewReportError.vue')['default']
  }
}
