// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Contributors: typeof import('./src/components/Contributors.vue')['default']
    DevelopmentWarning: typeof import('./src/components/DevelopmentWarning.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
  }
}

export { }
