// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contributors: typeof import('./src/components/Contributors.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMember: typeof import('./src/components/TeamMember.vue')['default']
  }
}

export {}
