name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  close-stale:
    runs-on: ubuntu-slim
    name: Close Marked Issues and PRs
    permissions:
      contents: read # to check out the repo for local actions
      issues: write # to close issues
      pull-requests: write # to close pull requests
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: needs reproduction
        uses: ./.github/actions/issues-helper
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs reproduction
          inactive-day: 3
      - name: maybe automated
        uses: ./.github/actions/issues-helper
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: maybe automated
          inactive-day: 3
