name: Label Automated PR

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, '<!-- VITEST_AUTOMATED_PR -->')
    steps:
      - name: maybe automated
        uses: actions-cool/issues-helper@71b62d7da76e59ff7b193904feb6e77d4dbb2777 # v3.7.6
        with:
          actions: add-labels
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: maybe automated
