name: Prepare Publish

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Release target branch.
        required: true
        default: main
        type: string
      release:
        description: Bumpp release type.
        required: true
        default: next
        type: choice
        options:
          - next
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
      version:
        description: Specify exact version instead of bumpp release type
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.target_branch }}-${{ inputs.version || inputs.release }}
  cancel-in-progress: false

permissions: {}

env:
  VITE_TEST_WATCHER_DEBUG: 'false'

jobs:
  prepare:
    if: github.repository == 'vitest-dev/vitest'
    name: Prepare release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write # push the generated prepare branch
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set node version to 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      # TODO: for now, this step only outputs a compare URL for maintainers to manually create a PR from.
      # In the future, PR creation can be automated by using a Github App token like .github/workflows/ecosystem-ci-trigger.yml.
      - name: Prepare release branch
        id: prepare
        env:
          TARGET_BRANCH: ${{ inputs.target_branch }}
          RELEASE_TYPE: ${{ inputs.release }}
          RELEASE_VERSION: ${{ inputs.version }}
          RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_INPUT="${RELEASE_VERSION:-$RELEASE_TYPE}"
          PREPARE_BRANCH="prepare-$TARGET_BRANCH-$RELEASE_INPUT-$RUN_ID"
          git switch -c "$PREPARE_BRANCH"
          git config user.name "vitest-release-bot"
          git config user.email "actions@github.com"
          pnpm run release
          git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" "HEAD:$PREPARE_BRANCH"
          COMPARE_URL="https://github.com/vitest-dev/vitest/compare/$TARGET_BRANCH...$PREPARE_BRANCH?expand=1"
          echo "::notice title=Open release PR::$COMPARE_URL"
