name: Test Tag Push

on:
  push:
    branches:
      - test-release-tag-app-token

permissions: {}

jobs:
  test-tag:
    if: github.repository == 'vitest-dev/vitest'
    name: Test release tag push
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Push and delete test tag
        env:
          # GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v0.0.0-test.${GITHUB_RUN_ID}.${GITHUB_RUN_ATTEMPT}"
          git config user.name "vitest-release-bot[bot]"
          git config user.email "292707936+vitest-release-bot[bot]@users.noreply.github.com"
          git tag "$TAG" "$GITHUB_SHA"
          git push "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" "$TAG"
          git push "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" ":refs/tags/$TAG"
